version: "2"
services:
  doclever:
    # image: lw96/doclever:latest-alpine
    # build from ./Dockerfile
    build: .
    restart: always
    container_name: "doclever"
    ports:
    - 10000:10000
    volumes:
    - /usr/local/opt/app/doclever/file:/root/DOClever/data/file
    - /usr/local/opt/app/doclever/img:/root/DOClever/data/img
    - /usr/local/opt/app/doclever/tmp:/root/DOClever/data/tmp
    environment:
    # - DB_HOST=mongodb://localhost:27017/DOClever
    - PORT=10000
    links:
    - mongo:mongo

  mongo:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
#    If you need to store your database to local please add these two lines, and define your local data direction.
#    volumes:
#    - /my/own/datadir:/data/db
    

    
